-- Create anggota table
CREATE TABLE IF NOT EXISTS anggota (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  role TEXT DEFAULT 'member',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE anggota ENABLE ROW LEVEL SECURITY;

-- Create policy for read access (all authenticated users can read)
CREATE POLICY "Anggota are viewable by everyone" ON anggota FOR SELECT USING (true);

-- Create policy for insert (only authenticated users can insert)
CREATE POLICY "Anggota can be inserted by authenticated users" ON anggota FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create policy for update (only authenticated users can update)
CREATE POLICY "Anggota can be updated by authenticated users" ON anggota FOR UPDATE USING (auth.role() = 'authenticated');

-- Insert initial user RAMA
INSERT INTO anggota (name, phone, role)
VALUES ('RAMA', '082122451622', 'admin')
ON CONFLICT (phone) DO NOTHING;
